version: '3'

services:
  postgres:
    image: postgres:16rc1-alpine3.18
    environment:
      POSTGRES_PASSWORD: smapi
      POSTGRES_DB: space_mission_api
    ports:
      - '5432:5432'

  node:
    image: nicolaslima99/space-mission-api
    working_dir: /app
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    command: ['npm', 'start']
