openapi: 3.0.0
info:
  title: Space Mission API
  summary: A space mission manager
  description: Simple server where users can schedule missions to habitable planets
  version: 1.0.0
server:
  - url: https://localhost:3000/v1
    description: Main development server
license:
  name: MIT
  url: https://github.com/wnicolass/nasa-ztm-ts/blob/main/LICENSE.md
